### ISSUE TITLE
Is the bno080 optional?

### ISSUE THREAD

**Issue by rcdemuth** [jangleboom/RTKRover#1]
So, I'm trying to put together a rover.  I don't have one of the bno080 boards, and was wondering what it's role was.

**Comment by jangleboom** [comment]
Hello rcdemuth, no – it is optional. However, if you don't want to use orientation tracking, you should comment out all of the associated BNO080 code. The device was built for an audio art project in acoustic virtual reality. In order to reproduce the sound dynamically depending on position and viewing direction, we needed both the BNO080 data and the GPS data. To use just the rover you don't need a BNO080.
